tls:
  certificates:
    - certFile: /certs/traefik.localhost.pem
      keyFile: /certs/traefik.localhost-key.pem
    - certFile: /certs/mailpit.localhost.pem
      keyFile: /certs/mailpit.localhost-key.pem
