master:
  path: ~/phpdev
  composeFileName: docker-compose.yml

projects:
  - name: api-gateway
    path: ~/code/php/api-gateway
    composeFileName: docker-compose-dev-tls.yml
    appContainer: api-fpm
    webContainer: api-gateway-nginx

  - name: status-notification-service
    path: ~/code/php/status-notification-service
    composeFileName: docker-compose-dev-tls.yml
    appContainer: sns-fpm
    webContainer: status-notification-service-nginx

  - name: endeavour-production
    path: ~/code/php/endeavour-production
    composeFileName: docker-compose-dev-tls.yml
    appContainer: endeavour-fpm
    webContainer: endeavour-production-nginx

